name: barcamp
description: Seattle Barcamp 2019 website.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  link: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/froggie.png
    - assets/images/cal.png
    - assets/images/map.png
    - assets/images/whatis.jpg
    - assets/images/stickers.png
    - assets/images/flutter.png
    - assets/images/github.png
  fonts:
     - family: Montserrat
       fonts:
         - asset: fonts/Montserrat-Regular.ttf
         - asset: fonts/Montserrat-Italic.ttf
           style: italic
         - asset: fonts/Montserrat-Bold.ttf
           weight: 700
     - family: RockSalt
       fonts:
         - asset: fonts/RockSalt-Regular.ttf
